spring:
  datasource:
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev
  http:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
security:
  oauth2:
    client:
      client-id: web
  basic:
    enabled: false
server:
  port: 9077
logging:
  level:
    root: info
#    org.springframework.security: trace
#    org.springframework.security.oauth2: INFO
---
storage:
  location:
spring:/amourling/images/
  profiles: prod
  datasource:
   password: OGfwX2xPDNj0oRdy
   url: jdbc:mysql://mysql2service:3306/space01?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&autoReconnectForPools=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useSSL=false
security:
  oauth2:
    client:
      access-token-uri: https://sec.amourling.cn/uaa/oauth/token
    resource:
      user-info-uri: https://sec.amourling.cn/uaa/me
---
storage:
  location: /Users/wenqi/Develop/images
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/space?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&autoReconnectForPools=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useSSL=false
    password: root
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8080/uaa/oauth/token
    resource:
      user-info-uri: http://localhost:8080/uaa/me
