spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/space?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&autoReconnectForPools=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev
security:
  oauth2:
    client:
      client-id: web
      access-token-uri: http://localhost:8080/uaa/oauth/token
    resource:
      user-info-uri: http://localhost:8080/uaa/me
  basic:
    enabled: false
server:
  port: 9077
logging:
  level:
    root: info
    org.springframework.security: trace
    org.springframework.security.oauth2: INFO
---
storage:
  location: /amourling/images/
spring:
  profiles: prod
---
storage:
  location: /Users/wenqi/Develop/images
spring:
  profiles: dev
