version: '3.3'
services:
  mysql2service:
    image: mysql:5.6
    container_name: mysql2service
    ports:
      - "3336:3306"
    environment:
        MYSQL_DATABASE: space01
        MYSQL_ROOT_PASSWORD: OGfwX2xPDNj0oRdy
  oauth2server:
    build: .
    ports:
      - "9077:9077"
    depends_on:
      - mysql2service
    environment:
      SPRING_PROFILES_ACTIVE: prod


