server:
  port: 8002
security:
  oauth2:
    client:
      client-id: web
      client-secret: web_secret
      scope: role_superadmin
      grant-type: authorization_code
  basic:
    enabled: false
spring:
  thymeleaf:
    mode: LEGACYHTML5
  datasource:
    username: root
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  http:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
logging:
  level:
    root: info
---
security:
  oauth2:
    client:
      access-token-uri: https://sec.amourling.cn/uaa/oauth/token
      user-authorization-uri: https://sec.amourling.cn/uaa/oauth/authorize
      use-current-uri: false
      pre-established-redirect-uri: https://res.amourling.cn/login
    resource:
     user-info-uri: https://sec.amourling.cn/uaa/me
storage:
  location: /opt/res
spring:
  profiles: prod
  datasource:
    password: OGfwX2xPDNj0oRdy
    url: jdbc:mysql://mysql2service:3306/space01?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&autoReconnectForPools=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useSSL=false
---
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8080/uaa/oauth/token
      user-authorization-uri: http://localhost:8080/uaa/oauth/authorize
    resource:
     user-info-uri: http://localhost:8080/uaa/me
storage:
  location: /Users/wenqi/Develop/images
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/space?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&autoReconnectForPools=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useSSL=false
    password: root