server:
  port: 8002
  session:
    cookie:
      name: APPSESSIONID
security:
  oauth2:
    client:
      client-id: web
      client-secret: web_secret
      scope: read,write
      grant-type: authorization_code
  basic:
    enabled: false
spring:
  thymeleaf:
    mode: LEGACYHTML5
  http:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
logging:
  level:
    root: info
#    org.springframework.security: trace
#    org.springframework.security.oauth2: INFO
---
security:
  oauth2:
    client:
      access-token-uri: https://sec.amourling.cn/uaa/oauth/token
      user-authorization-uri: https://sec.amourling.cn/uaa/oauth/authorize
    resource:
     user-info-uri: https://sec.amourling.cn/uaa/me
spring:
  profiles: prod
url:
  api: https://service.amourling.cn
  oauth2: https://sec.amourling.cn/uaa
---
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8080/uaa/oauth/token
      user-authorization-uri: http://localhost:8080/uaa/oauth/authorize
    resource:
     user-info-uri: http://localhost:8080/uaa/me
spring:
  profiles: dev
url:
  api: http://localhost:9077
  oauth2: http://localhost:8080/uaa
