spring:
  datasource:
    username: space
    password: space2018
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysqlserver:3306/space?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&rewriteBatchedStatements=TRUE&autoReconnectForPools=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useSSL=false
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  resources:
    add-mappings: true
server:
  port: 8080
  context-path: /uaa
security:
  sessions: stateless
logging:
  level:
    root: info
    org.springframework.security: trace
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

